### ISSUE TITLE
Anemoy currency migration MVP

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#2001] opened 2024-03-06 15:22 UTC
[Specs](https://centrifuge.hackmd.io/oFV5suFaQ7W9mNO7jAG-YA)
[Figma designs](https://www.figma.com/file/cn5CiQsuVDOmieszqcneX2/Pool-management?type=design&node-id=850-19630&mode=design&t=WEvUll1AfVlNbY8y-0)
[Protocol PR](https://github.com/centrifuge/centrifuge-chain/pull/1713)

## Background
To streamline the swapping process, issuers can avoid swapping 1 million at a time by directly exchanging funds between onchain and the offramp accounts. A new pool currency is introduced `LocalUSDC`. 

Protocol circle built a pallet that is able to lock variants of the same foreign asset and mints the respective local representation of these variants `LocalUSDC`. The reverse process would be burn local representation and release variant token.

### Swaps UI
For the UI it is important to differentiate between the direction of the swap, when handling `LocalUSDC`.

#### `Variant` to `LocalUSDC`
This means swapping for example `LpEthUSDC` > `LocalUSDC`. If such a swap is detected, then the swaps page in the UI MUST call `pallet_token_mux::match_oder(OrderId, Amount)`.

* the `pallet_token_mux` will mint the respective amount of `LocalUSDC`
* the `pallet_token_mux` will lock the respective amount of `Variant`

NOTE: 
* UI can fetch full order amount from `pallet_order_book`

#### `LocalUSDC` to `Variant`
This means swapping for example `LocalUSDC` > `LpEthUSDC`. If such a swap is detected, then the UI must
* check how much `LpEthUSDC` does the `pallet_token_mux::PalletID`-account hold - this indicates the maximum amount that can be swapped
* use `pallet_token_mux::match_oder(OrderId, Amount)` to fulfill the order - where `Amount` can be at most the above queried value

### Off-Ramping
Additionally to the above needed changes for swapping, a pool that is having `LocalUSDC` also needs to handle `borrow` with additional care. The reason is that one can off-ramp over all domains that have a valid `Variant` for `LocalUSDC` - e.g. `AssetHub` or `Ethereum` or `Base` or etc.

The problem is that  the amount to off-ramp is limited by the amount that is currently hold by the  `pallet_token_mux::PalletID`-account of the off-ramping currency. 

E.g. 
* `pallet_token_mux::PalletID`- account holds `7`-`LpCeloUSDC` and `3`-`LpEthUSDC`
* issuer wants to `borrow` `5`-`LocalUSDC`

The call for the above should be:
* batch of `borrow(TOTAL_AMOUNT)`, `create_order(LocalUSDC, Variant, PORTION_OF_AMOUNT)`, `match_order(..)`,  `create_order(LocalUSDC, Variant, PORTION_OF_AMOUNT)`, `match_order(..)`, ... 

* We don't allow the issuer to set the amounts that get send to a specific network in the MVP and decide for them where the funds get sent. 
* Priority list (cheapest to most expensive network)
    1. Base
    2. Asset Hub
    3. Celo
    4. Ethereum
 
## Design 

<img width="568" alt="Screenshot 2024-03-11 at 16 30 08" src="https://github.com/centrifuge/apps/assets/31280003/b992a405-cf68-4fc8-9420-331a652cbc8f">

**Comment by mustermeiszer** [comment] 2024-03-06 16:35
For this change there are 3 main areas that need changes: 

# Swaps UI
For the UI it is important to differentiate between the direction of the swap, when handling `LocalUSDC`.

## `Variant` to `LocalUSDC`
This means swapping for example `LpEthUSDC` > `LocalUSDC`. If such a swap is detected, then the swaps page in the UI MUST call `pallet_token_mux::match_oder(OrderId, Amount)`.

* the `pallet_token_mux` will mint the respective amount of `LocalUSDC`
* the `pallet_token_mux` will lock the respective amount of `Variant`

NOTE: 
* UI can fetch full order amount from `pallet_order_book`

## `LocalUSDC` to `Variant`
This means swapping for example `LocalUSDC` > `LpEthUSDC`. If such a swap is detected, then the UI must
* check how much `LpEthUSDC` does the `pallet_token_mux::PalletID`-account hold - this indicates the maximum amount that can be swapped
* use `pallet_token_mux::match_oder(OrderId, Amount)` to fulfill the order - where `Amount` can be at most the above queried value


# On-Ramping
Additionally to the above needed changes for swapping, a pool that is having `LocalUSDC` also needs to handle `repay` with additional care. The reason is that one can `repay` from all valid domains that host a valid `Variant` for `LocalUSDC` - e.g. `AssetHub` or `Ethereum` or `Base` or etc. 

The problem is that onboarding is a two step process:
1. Transfer assets from domain to `Centrifuge`
2. BatchAll of `create_order(Variant, LocalUSDC, Amount)`, `match_order(OrderId, Amount)`,  `repay(..)`

NOTE: 
The `OrderId` is quasi deterministic, but the call can fail if another order is created before the batch call.

NOTE 2: 
In the future an Issuer will want to on-ramp over multiple domains IF there are redemptions coming from all of these domains. E.g. 
* Token Price `1`
* Redemptions
  * `Celo` = `10`
  * `Ethereum` = `15`
In these case it would be great if the UI could show that the issuer should on-ramp `10`-`LpCeloUSDC` and `15`-`LpEthUSDC` as this would allow investors to easily get their redemptions out from `Centrifuge`.

# Off-Ramping
Additionally to the above needed changes for swapping, a pool that is having `LocalUSDC` also needs to handle `borrow` with additional care. The reason is that one can off-ramp over all domains that have a valid `Variant` for `LocalUSDC` - e.g. `AssetHub` or `Ethereum` or `Base` or etc.

The problem is that  the amount to off-ramp is limited by the amount that is currently hold by the  `pallet_token_mux::PalletID`-account of the said off-ramping currency. 

E.g. 
* `pallet_token_mux::PalletID`-account holds `7`-`LpCeloUSDC` and `3`-`LpEthUSDC`
* issuer wants to `borrow` `5`-`LocalUSDC`

The UI needs to show that off-ramping all via `Ethereum` is not possible in this case. The best would be if the UI shows the maximum amount + the maximum amount per domain. Then the user can decide what amount will be off-ramped over which domain. Being able to choose different addresses per domain is essential here. 

The call for the above should be:
* batch of `borrow(TOTAL_AMOUNT)`, `create_order(LocalUSDC, Variant, PORTION_OF_AMOUNT)`, `match_order(..)`,  `create_order(LocalUSDC, Variant, PORTION_OF_AMOUNT)`, `match_order(..)`, ...

**Comment by onnovisser** [comment] 2024-03-26 10:14
@annamehr to test this

- Have a pool with localUSDC with assets, there's a "Local USDC Pool" on Demo.
- Have withdraw addresses set to different domains, e.g. Base, Sepolia, Arbitrum
- Swap sepolia/base/...USDC for localUSDC in PolkadotJS via `tokenMux.deposit` (foreign assets are Base: 100002, Arbitrum: 100003, Celo: 100004, Sepolia: 100005) (They all have 6 decimals) (Charlie has a balance for all of them)
- The account you swapped with will now have localUSDC you can invest into the pool, and the tokenMux pallet will now have those currencies you've swapped in it's reserve that can be used when financing a loan
- Finance a loan, it should distribute the finance amount between the currencies in the tokenMux reserve, as long as you have withdraw addresses set for those currencies. If successful it should've also transferred the amounts to their respective domains.

**Closed as completed** 2024-04-05 09:28 UTC
