### ISSUE TITLE
After investing, tokens do not show up in the portfolio immediately

### ISSUE THREAD

**Issue by philipstanislaus** [centrifuge/apps#160] opened 2021-03-15 10:06 UTC
We currently fetch daily updated values from the subgraph. That should change such that we use real-time data to not confuse users.

**Comment by offerijns** [comment] 2021-03-24 12:09
I think this is a duplicate of https://github.com/centrifuge/apps/issues/113

**Closed by offerijns** 2021-03-24 12:09 UTC
