### ISSUE TITLE
Onboarding bugs

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1385] opened 2023-05-16 16:03 UTC
1. In onboarding first step (Connect and link your wallet), if I deny the signing the first time, the ‘Continue’ button doesn’t work or give an error. In console, I see “MetaMask - RPC Error: MetaMask Personal Message Signature: User denied message signature.” — but I cannot get it to show the signing modal again unless I disconnect and reconnect my wallet.

2. If MetaMask auto-locks, it kicks me back to the start of onboarding. When I unlock metamask again, it kicks me back to the beginning of step 3, and I have to upload my ID/address/face again. :( It’s impossible to finish onboarding within MetaMask’s default lock out timer (3 minutes) with the time it takes to upload/verify documents — had to increase lock out time in MetaMask settings -> Advanced

----> can we increase the lock out time on our end?

4. Bug:  In onboarding step 3, I get a “please enter a valid email” error next to my email even though it’s a valid email. 

----> remove error when valid email is entered 

6. Not clear what to do if verification fails (e.g. due to a blurry photo). It's not clear that I can go back (and start over the whole uploading process again) by clicking on the icons at the left. 

---> add hint that user can go back and reupload documents
"If verification fails, please return and try uploading the requested documents again."

7. **Blocking issue (can’t finish onboarding): verify email link in KYC process leads to a link with an invalid cert: ** https://url8881.centrifuge.io/ls/click?upn=jx-2BPv7Ftmn-2F-2Bh-2ByvUzgBDn8Wt7y2ofI1cH3Bxr2OHAyGFFEJrv5QYMM3v4C72bvAID-2BkKsUEK-2BOVxPRURoKYrq4kMjDyc1JprbvKJnpCwctadzxG7FrPPXJMBxMZJ17oqzxrGFrIjh-2FrUPEo-2FABvUHbsTcNkMnNxq-2BE34VsMgpjOF4jbjSua9z-2Fxlsi9K-2BLgJ8ovebioS69Fu7cPFyrgU-2BQGU116oUbmAH6-2FJFEMr7thz-2B-2FmfAuxLQRiOkYZ0LQH3UPCRmQG54-2FAH1D8z-2BX4kNvRed5THC9eT9-2BQ-2Fu1t2fObjgvkhaQTrz2bitb6qhpxBAddthY6SS0KFeo-2FqIZJnNxEQ84mEfX6Awq5L2roaf9d2WxYpLaSjpR2l0aeVzKwoEi5L9LBJGbG7GlhRMCg3vSFutw88S-2BWGPqprywpZlI4H18kDX-2FIgyKB3CAHx5YD-2FVWv3Jm9JXqUr3a63N7auw-3D-3DhF8O_l7T1evsdeDpAdsYrmPx66ewD8O99Z6UGphVd0hTFToK3HvDDjSlw7YX-2B4slyMLySq-2FSnRRwX1s-2Bv-2FKUy144gTOrBx5XiqHy6Bh6j1vIHEplH7xYcLhAaWzZ7IR5CwYiu89xnki6rv2JN5HoP2pBIbTsK8UiDlU2natNUah8-2BxoUhj2CG2RRI1l54EhnluTJmaEYkjuWHg4qx5EJBecyPfyK9KgieqTBf3oUlL1t-2BylVkSvm2iVPqPuumep0ifIepLGy7RCCzPPhkjoOXm7UwLjmznBUJ3tSwlkSbqEPbzFa6RYGbtMHY8CTePlglA4qtw1J-2FzEF0MclKlf8o3a9-2BJw-3D-3D

8. In the KYC email verification email, the “investment disclaimer” and “privacy policy” hyperlinks lead to a link with an invalid certificate, example being for investment disclaimer: https://url8881.centrifuge.io/ls/click?upn=jx-2BPv7Ftmn-2F-2Bh-2ByvUzgBDo3CgyyNtIV7NG6R-2ByQOc2Ae6r6fLyBVvQwBKO-2BOCJHEn40HwjYcmuRxsNid-2FUB8qgopdEBbOi1xz88ewyb3j5c-3DIsuc_l7T1evsdeDpAdsYrmPx66ewD8O99Z6UGphVd0hTFToK3HvDDjSlw7YX-2B4slyMLySq-2FSnRRwX1s-2Bv-2FKUy144gTOrBx5XiqHy6Bh6j1vIHEplH7xYcLhAaWzZ7IR5CwYiu89xnki6rv2JN5HoP2pBIbTsK8UiDlU2natNUah8-2BxoUhj2CG2RRI1l54EhnluTJm3RWRNyuQB693yBKGSo9-2BdHXRnFqHKuvOXjkBc26LTfT7eQ7dXH6AXeTFJjb5OKw-2BQmedl21AmbVK1-2BHsL1LfDJZD2Gbpmon-2BbJr5xjxqw0Ow3qTFpzZ7F1HOZp9DjmrwyRxHhiKMKvsecelj0YqI5Q-3D-3D

9. “Next” button is already active before tax document is uploaded. 
![image](https://github.com/centrifuge/apps/assets/31280003/441a9349-6b69-4820-bc15-4d12efb182ea)

**Comment by sophialittlejohn** [comment] 2023-05-17 22:49
> 1. In onboarding first step (Connect and link your wallet), if I deny the signing the first time, the ‘Continue’ button doesn’t work or give an error. In console, I see “MetaMask - RPC Error: MetaMask Personal Message Signature: User denied message signature.” — but I cannot get it to show the signing modal again unless I disconnect and reconnect my wallet.

I couldn't reproduce, if I decline the signature and click Continue the modal shows up.

> 2. If MetaMask auto-locks, it kicks me back to the start of onboarding. When I unlock metamask again, it kicks me back to the beginning of step 3, and I have to upload my ID/address/face again. :( It’s impossible to finish onboarding within MetaMask’s default lock out timer (3 minutes) with the time it takes to upload/verify documents — had to increase lock out time in MetaMask settings -> Advanced

I don't think we can increase the time. When the wallet is disconnected due to auto lock, authentication to the onboarding-api will fail. It might make sense at some point in the journey to warn the user to increase auto locks. But I'd say that something we can look into after the launch. 

> 4. Bug: In onboarding step 3, I get a “please enter a valid email” error next to my email even though it’s a valid email.

I think that was intended to be a permanent tooltip. I changed the color of the font so it doesn't look like an error anymore! Addressed in PR #1388 

> 6. Not clear what to do if verification fails (e.g. due to a blurry photo). It's not clear that I can go back (and start over the whole uploading process again) by clicking on the icons at the left.

Added a button to click to restart verification if KYC fails.
Addressed in PR #1388 

> 7. 8. invalid certs

Passed the issue to devops. It appears the SSL cert on our SendGrid proxy expired.

> 9. “Next” button is already active before tax document is uploaded.
Addressed in PR #1388

**Closed** 2023-05-18 16:55 UTC
Labels: bug
