### ISSUE TITLE
Hide `Lock NFT` button on asset tab for non-borrowers

### ISSUE THREAD

**Issue by denniswell** [centrifuge/apps#65] opened 2020-12-17 22:07 UTC
This button is confusing for people not being the AO.

As at the moment through our oracle set-up only a whitelisted address can actually draw down financings in Tinlake, we should only show the button to the borrower address. Not sure how we could capture that at the moment. The address is whitelisted in the oracle contract, not sure if we can grab it from there

**Comment by offerijns** [comment] 2020-12-17 22:23
This is a duplicate of https://github.com/centrifuge/apps/issues/43 :)

**Closed** 2021-03-29 13:51 UTC
